In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
# engine = create_engine(
# "postgresql+psycopg2://postgres:yourpassword@localhost:port_number/database"
# )

In [4]:
with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [5]:
from pathlib import Path

PROJECT_DIR = Path.cwd().parent
DATA_DIR = PROJECT_DIR / "data_raw"

customers = pd.read_csv(
    DATA_DIR / "olist_customers_dataset.csv"
)

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [11]:
customers = pd.read_csv(r"C:\Users\rbray\OneDrive\Desktop\data projs\archive (1)\olist_customers_dataset.csv")

In [6]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [7]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [8]:
customers.shape

(99441, 5)

In [9]:
customers.to_sql(
    name="customers",
    con=engine,
    schema="raw",
    if_exists="replace",
    index=False
)

441

In [10]:
pd.read_sql(
    "SELECT * FROM raw.customers LIMIT 5",
    engine
)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [11]:
pd.read_sql(
    "SELECT COUNT(*) AS row_count FROM raw.customers",
    engine
)

   row_count
0      99441

In [19]:
customers.to_sql(
    name="customers",
    con=engine,
    schema='raw',
    if_exists='replace',
    index=False
)

441

In [15]:
from pathlib import Path

# data_dir = Path(r"C:\Users\rbray\OneDrive\Desktop\data projs\archive (1)")

files = {
    "customers": "olist_customers_dataset.csv",
    "orders": "olist_orders_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "payments": "olist_order_payments_dataset.csv",
    "products": "olist_products_dataset.csv",
    "reviews": "olist_order_reviews_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "geolocation": "olist_geolocation_dataset.csv",
    "category_translation": "product_category_name_translation.csv",
}

In [16]:
def load_table(table_name, filename):
    filepath = DATA_DIR / filename

    print(f"Loading {table_name}...")

    df = pd.read_csv(filepath)

    df.to_sql(
        name=table_name,
        con=engine,
        schema="raw",
        if_exists="replace",
        index=False
    )

    print(f"Loaded {len(df):,} rows into raw.{table_name}")

    return df

In [17]:
def load_table(table_name,file_name):
    filepath=DATA_DIR/file_name
    print(f"Loading {table_name}..")
    df=pd.read_csv(filepath)
    df.to_sql(
        name=table_name,
        con=engine,
        schema="raw",
        if_exists="replace",
        index=False
    )
    print(f"Loaded {len(df):,} rows into raw.{table_name}")

    return df

In [18]:
loaded_tables={}

for table_name,file_name in files.items():
    loaded_tables[table_name]=load_table(table_name,file_name)

Loading customers..
Loaded 99,441 rows into raw.customers
Loading orders..
Loaded 99,441 rows into raw.orders
Loading order_items..
Loaded 112,650 rows into raw.order_items
Loading payments..
Loaded 103,886 rows into raw.payments
Loading products..
Loaded 32,951 rows into raw.products
Loading reviews..
Loaded 99,224 rows into raw.reviews
Loading sellers..
Loaded 3,095 rows into raw.sellers
Loading geolocation..
Loaded 1,000,163 rows into raw.geolocation
Loading category_translation..
Loaded 71 rows into raw.category_translation

In [20]:
pd.read_sql(
    "SELECT * FROM raw.orders LIMIT 5",
    engine
)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [21]:
pd.read_sql(
    "SELECT COUNT(*) AS row_count FROM raw.orders",
    engine
)

   row_count
0      99441